-- ════════════════════════════════════════════════════════════════════════
-- 034 — Module « Gestion des risques de péremption » — PHASE 1 (matrice de scoring)
-- ════════════════════════════════════════════════════════════════════════
-- 3 axes (Produit / Partenaire / Marché), 9 sous-critères scorés 1/3/5.
-- Score d'axe = moyenne de ses sous-critères ; score global = pondération
-- (Produit 25% / Partenaire 25% / Marché 50% par défaut, configurable).
-- Niveau (3 paliers alignés sur 1/3/5) : ≤ seuil_moyen = Faible ·
-- ≤ seuil_eleve = Moyen · sinon Élevé.
-- ⚠️ RÈGLE N°13 : 4 policies RLS / table.  RÈGLE N°18 : FK vers products.
-- À exécuter dans Supabase SQL Editor (un seul bloc, aucun ALTER TYPE ici).

-- ── 1. Configuration (pondérations + seuils) : table à 1 ligne ──────────────
CREATE TABLE IF NOT EXISTS public.peremption_config (
  id               smallint PRIMARY KEY DEFAULT 1,
  poids_produit    numeric NOT NULL DEFAULT 25,
  poids_partenaire numeric NOT NULL DEFAULT 25,
  poids_marche     numeric NOT NULL DEFAULT 50,
  seuil_moyen      numeric NOT NULL DEFAULT 2,   -- global <= seuil_moyen  → Faible
  seuil_eleve      numeric NOT NULL DEFAULT 4,   -- global <= seuil_eleve  → Moyen ; sinon Élevé
  updated_at       timestamptz DEFAULT now(),
  updated_by       uuid,
  CONSTRAINT peremption_config_single CHECK (id = 1)
);
INSERT INTO public.peremption_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ── 2. Évaluations (append → historique ; « courant » = dernière par produit) ─
CREATE TABLE IF NOT EXISTS public.peremption_evaluations (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  mode_appro     text,            -- sous_licence | import | les_deux | generique
  -- 9 sous-scores (1 / 3 / 5)
  sc_shelf_life  smallint,
  sc_prix        smallint,
  sc_historique  smallint,
  sc_forecast    smallint,        -- binaire 1/5
  sc_solvabilite smallint,
  sc_engagements smallint,
  sc_croissance  smallint,
  sc_concurrence smallint,
  sc_maturite    smallint,        -- binaire 1/5
  -- scores calculés (figés à l'enregistrement, pour cohérence d'historique)
  score_produit    numeric,
  score_partenaire numeric,
  score_marche     numeric,
  score_global     numeric,
  niveau           text,          -- faible | moyen | eleve
  note           text,
  evaluated_by   uuid,
  evaluated_at   timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_peremption_eval_product
  ON public.peremption_evaluations(product_id, evaluated_at DESC);

-- ── 3. RLS — 4 policies / table (RÈGLE N°13) ────────────────────────────────
ALTER TABLE public.peremption_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "rls_peremption_config_select" ON public.peremption_config FOR SELECT TO authenticated USING (true);
CREATE POLICY "rls_peremption_config_insert" ON public.peremption_config FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "rls_peremption_config_update" ON public.peremption_config FOR UPDATE TO authenticated USING (true);
CREATE POLICY "rls_peremption_config_delete" ON public.peremption_config FOR DELETE TO authenticated USING (true);

ALTER TABLE public.peremption_evaluations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "rls_peremption_eval_select" ON public.peremption_evaluations FOR SELECT TO authenticated USING (true);
CREATE POLICY "rls_peremption_eval_insert" ON public.peremption_evaluations FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "rls_peremption_eval_update" ON public.peremption_evaluations FOR UPDATE TO authenticated USING (true);
CREATE POLICY "rls_peremption_eval_delete" ON public.peremption_evaluations FOR DELETE TO authenticated USING (true);

-- ── 4. Permission applicative ───────────────────────────────────────────────
-- Clé : evaluer_risque_peremption (catalogue déclaré dans AdminPermissionsPage).
-- L'admin a un bypass global (permissions.js l.18) ; les autres services se
-- voient accorder la permission via l'écran Admin → Permissions (insert ci-dessous
-- optionnel pour pré-activer un service, ex. planification) :
-- INSERT INTO public.permissions (service, action, allowed)
-- VALUES ('planification', 'evaluer_risque_peremption', true)
-- ON CONFLICT (service, action) DO UPDATE SET allowed = true;
